# _quarto.yml
project:
  type: website

website:
  title: "UFPA - Raphael Teixeira"
  description: "Página pessoal para ensino e pesquisa."
  site-url: https://raphateixeira.github.io

  # Barra de Navegação Principal (Navbar)
  navbar:
    background: "#002C6F" # Azul UFPA
    foreground: "#FFFFFF"
    left:
      - text: "Início"
        href: index.qmd
      - text: "Ensino"
        href: Ensino/index.qmd
      - text: "Pesquisa"
        href: Pesquisa/index.qmd
      - text: "Publicações"
        href: Publicacoes/index.qmd
      - text: "Notas"
        href: Notas/index.qmd
      - text: "Estudos"
        href: Estudos/index.qmd
    right:
      - icon: github
        href: https://github.com/raphateixeira
      - icon: envelope
        href: mailto:raphaelbt@ufpa.br
        
  # BARRA LATERAL AUXILIAR (Sidebar) - CORRIGIDA
  sidebar:
    style: "docked" # Mantém a barra visível na esquerda
    search: false # Desativa a pesquisa lateral
    
    contents:
      - title: "Perfil"
        section: Perfil
        level: 1
        contents:
          - text: "<i class='bi bi-person-fill'></i> Lattes"
            href: "http://lattes.cnpq.br/4902824086591521" 
          - text: "<i class='bi bi-orcid'></i> Orcid"
            href: "https://orcid.org/0000-0003-2993-802X"
          - text: "<i class='bi bi-building'></i> PPCA - UFPA"
            href: "https://www.ppca.propesp.ufpa.br/index.php/br/"
            

            
  page-footer: 
    background: "#231F20" # Preto UFPA
    foreground: "#FFFFFF"
    left: "©2025 Prof. Dr. Raphael Teixeira"
    right: "Desenvolvido com Quarto"

format:
  html:
    theme:
      light: [cosmo, custom.scss]
    toc: true
    toc-title: "Tópicos da Página"
    code-block-border-left: "#E4002B"
    lang: pt