# .github/workflows/publish.yml

on:
  # Aciona o workflow quando h치 um push (envio de c칩digo) para o branch 'main'
  push:
    branches: [main]
  
  # Permite a execu칞칚o manual do workflow pela interface do GitHub (Bot칚o 'Run workflow')
  workflow_dispatch:

name: Quarto Publish

jobs:
  build-publish:
    # O workflow ser치 executado em um servidor virtual Ubuntu
    runs-on: ubuntu-latest
    
    # Permiss칫es necess치rias para que o workflow possa escrever e publicar no Pages
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: 游닌 Check out repository
        uses: actions/checkout@v4

      - name: 丘뙖잺 Set up Quarto
        # Instala o Quarto CLI no ambiente de execu칞칚o do GitHub Actions
        uses: quarto-dev/quarto-actions/setup@v2

      - name: 游냀 Set up Python and install dependencies
        # Instala a vers칚o 3.10 do Python e o cache de pacotes
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' 
          
      # Exemplo de instala칞칚o de pacotes comuns de Data Science
      - name: Install dependencies
        run: |
          pip install pandas numpy jupyterlab jupyter_client 
          # Use um arquivo requirements.txt se sua lista for longa!

      # 游눹 Renderiza e Publica
      - name: Render and Publish
        # Este passo executa 'quarto render' e envia o resultado para o GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: github-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}